apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
  # labels: 
  #   name: nginx
  #   version: blue
spec:
  type: LoadBalancer
  selector:
    name: nginx
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80